# Generated by Django 3.1.2 on 2020-10-03 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('sku', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('stock', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
            options={
                'db_table': 'product',
                'managed': True,
            },
        ),
    ]
