# Generated by Django 3.1.2 on 2020-10-03 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0002_auto_20201003_1740'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kit',
            fields=[
                ('sku', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'kit',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='KitProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('discount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_sku', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='product.product')),
            ],
            options={
                'db_table': 'kit_products',
                'managed': True,
            },
        ),
    ]
