# Generated by Django 3.1.2 on 2020-10-03 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20201003_1740'),
        ('kit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitproduct',
            name='kit_sku',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='kit.kit'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kitproduct',
            name='product_sku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.product'),
        ),
    ]
