# Generated by Django 3.1.2 on 2020-10-03 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kit', '0002_auto_20201003_1830'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kitproduct',
            old_name='kit_sku',
            new_name='kit',
        ),
        migrations.RenameField(
            model_name='kitproduct',
            old_name='product_sku',
            new_name='product',
        ),
    ]
