# Generated by Django 3.1.2 on 2020-10-04 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kit', '0003_auto_20201003_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kit',
            name='sku',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='kitproduct',
            name='kit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kit.kit'),
        ),
    ]
